const assert = require('node:assert/strict')
const runtime = require('../shared/assessment-v3-product-v0/runtime-engine')
const { buildReport, buildEvidenceView } = require('../shared/assessment-v3-product/report-renderer')
const { deriveEligiblePatternIds } = require('../shared/assessment-v3-product/pattern-eligibility')
const { firstAnswers } = require('./assessment-v3-product-v0-runtime.test')

const profile = runtime.deriveProfile(firstAnswers())
const report = buildReport(profile)
assert.equal(report.source, 'THEORY_DRIVEN_PRODUCT_V0')
assert.equal(report.isSynthetic, false)
assert.equal(report.dimensionCards.length, 14)
assert.equal(report.chapterSyntheses.length, 6)
assert.equal(report.decisionMap.sections.map(section => section.id).join('|'), 'l3|l4|l5')
assert.ok(report.methodNote.body)
assert.ok(report.methodNote.body.includes('试用') || report.methodNote.body.includes('调整'))
assert.ok(report.executiveSummary.patterns.length <= 3)
assert.ok(report.executiveSummary.patterns.every(item => deriveEligiblePatternIds(profile).includes(item.id)))
assert.ok(report.dimensionCards.some(card => card.resultStatus === 'ESTIMATED'))
const evidenceCard = report.dimensionCards.find(card => card.evidenceAvailable)
assert.ok(evidenceCard)
const evidenceView = buildEvidenceView(report, evidenceCard.id)
assert.ok(evidenceView.evidence.every(item => item.question && item.answer))
assert.equal(JSON.stringify(report).includes('compatibility'), false)
assert.equal(JSON.stringify(report).includes('personalityType'), false)

const insufficient = buildReport(runtime.deriveProfile({}))
assert.ok(insufficient.dimensionCards.some(card => card.resultStatus === 'INSUFFICIENT'))
assert.equal(insufficient.dimensionCards.find(card => card.resultStatus === 'INSUFFICIENT').evidenceAvailable, false)

console.log('assessment-v3-product-v0 report tests OK: real profile, 14 dimensions, 6 chapters, evidence and insufficient copy')
