const assert = require('node:assert/strict')
const { ITEMS, CHAPTERS, getItem } = require('../utils/assessment-v2/questionnaire-definitions')
const { evaluateAssessment } = require('../utils/assessment-v2/scoring-engine')
const { buildReport } = require('../utils/assessment-v2/report-engine')
const { rules } = require('../utils/assessment-v2/report-rules')
const { buildChapterInsight } = require('../utils/assessment-v2/chapter-insight-engine')

assert.equal(ITEMS.length, 48)
assert.equal(CHAPTERS.length, 6)
CHAPTERS.forEach(chapter => assert.equal(chapter.itemIds.length, 8))
assert.equal(new Set(ITEMS.map(item => item.id)).size, 48)
assert.equal(rules.length, 19)
assert.equal(new Set(rules.map(rule => rule.id)).size, 19)

const allHigh = Object.fromEntries(ITEMS.map(item => [item.id, 5]))
const evaluation = evaluateAssessment(allHigh)
assert.equal(evaluation.dimensions.readiness_intent.state, 'mixed')
assert.equal(evaluation.dimensions.uncertainty_sensitivity.state, 'mixed')
assert.equal(evaluation.dimensions.response_predictability.needState, 'need_clear')
assert.equal(evaluation.dimensions.response_predictability.provideState, 'provide_stable')
assert.equal(evaluation.observations.REG03, 'active')

const reverseItem = getItem('RIN03')
assert.equal(reverseItem.reverseScored, true)
const supportive = Object.fromEntries(ITEMS.map(item => [item.id, item.reverseScored ? 1 : 5]))
assert.equal(evaluateAssessment(supportive).dimensions.readiness_intent.state, 'strong_present')
const missing = evaluateAssessment({ RIN01: 5, RIN02: 5 })
assert.equal(missing.dimensions.readiness_intent.state, 'insufficient')

const options = { generatedAt: 1000, reportVersion: 1 }
const expected = JSON.stringify(buildReport(allHigh, options))
for (let index = 0; index < 100; index += 1) assert.equal(JSON.stringify(buildReport(allHigh, options)), expected)
const report = JSON.parse(expected)
assert.ok(report.claims.every(claim => claim.evidence.supporting.every(entry => entry.itemId)))
assert.ok(report.claims.every(claim => claim.confidence && claim.confidence.level))
assert.ok(report.claims.every(claim => Array.isArray(claim.evidence.contradicting)))
assert.ok(report.allClaimCandidates.length >= report.claims.length)
assert.deepEqual(report.visibleClaimIds, report.claims.map(claim => claim.id))
assert.equal(report.claims.filter(claim => claim.section === 'observation').length, 2)
assert.ok(report.claims.some(claim => claim.id === 'OBS_REG03'))
assert.equal(report.claims.filter(claim => claim.section === 'provide').length, 2)
assert.ok(report.claims.filter(claim => claim.section === 'provide').every(claim => claim.evidence.supporting.length === 2))
assert.ok(report.claims.filter(claim => claim.section === 'provide').every(claim => claim.shareFragment))
assert.ok(report.claims.find(claim => claim.id === 'OBS_REG03').shareFragment)
assert.equal(report.instrumentVersion, '2.1.0-pilot')
assert.equal(buildChapterInsight('C1', supportive).chapterId, 'C1')

console.log('Assessment V2 OK: 48 items, 6 chapters, deterministic report')
