const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const crypto = require('node:crypto')

const root = path.resolve(__dirname, '..')
const source = fs.readFileSync(path.join(root, 'shared/assessment/schema.js'), 'utf8')
const digest = crypto.createHash('sha256').update(source).digest('hex')
const generated = [
  'utils/assessment-v2/generated/questionnaire-definitions.js',
  'cloudfunctions/datingProfile/assessment-v2-questionnaire-definitions.generated.js'
]
generated.forEach(file => assert.equal(fs.readFileSync(path.join(root, file), 'utf8'), source, file + ' is out of sync'))
const client = require('../utils/assessment-v2/questionnaire-definitions')
const cloud = require('../cloudfunctions/datingProfile/assessment-v2-questionnaire-definitions')
const versions = require('../shared/assessment/version')
const clientScoring = require('../utils/assessment-v2/scoring-engine')
const cloudScoring = require('../cloudfunctions/datingProfile/assessment-v2-scoring-engine')
const clientReportRules = require('../utils/assessment-v2/report-rules')
const cloudReportRules = require('../cloudfunctions/datingProfile/assessment-v2-report-rules')
assert.equal(client.INSTRUMENT_VERSION, '2.1.1-pilot')
assert.equal(client.INSTRUMENT_VERSION, versions.INSTRUMENT_VERSION)
assert.equal(clientScoring.SCORING_RULE_VERSION, versions.SCORING_RULE_VERSION)
assert.equal(cloudScoring.SCORING_RULE_VERSION, versions.SCORING_RULE_VERSION)
assert.equal(clientReportRules.REPORT_RULE_VERSION, versions.REPORT_RULE_VERSION)
assert.equal(cloudReportRules.REPORT_RULE_VERSION, versions.REPORT_RULE_VERSION)
assert.deepEqual(cloudReportRules.rules, clientReportRules.rules)
assert.equal(cloud.INSTRUMENT_VERSION, client.INSTRUMENT_VERSION)
assert.deepEqual(cloud.ITEMS, client.ITEMS)
assert.deepEqual(cloud.CHAPTERS, client.CHAPTERS)
assert.deepEqual(cloud.DIMENSIONS, client.DIMENSIONS)
assert.equal(client.ITEMS.length, 48)
assert.deepEqual(client.ITEMS.map(item => item.id), cloud.ITEMS.map(item => item.id))
assert.equal(JSON.parse(fs.readFileSync(path.join(root, 'shared/assessment/schema.manifest.json'), 'utf8')).sha256, digest)
console.log('Assessment schema sync OK: client/cloud definitions and hash match')
