const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { ITEMS } = require('../utils/assessment-v2/questionnaire-definitions')
const { buildReport } = require('../utils/assessment-v2/report-engine')
const { buildChapterInsight } = require('../utils/assessment-v2/chapter-insight-engine')
const { rules } = require('../utils/assessment-v2/report-rules')
const { resolveClaimCopy } = require('../shared/content/claim-copy')
const { CONTENT_VERSION, REPORT_COPY_VERSION } = require('../shared/content/version')
const { getChapterCopy } = require('../shared/content/chapter-copy')
const evidenceCopy = require('../shared/content/evidence-copy')

const answers = Object.fromEntries(ITEMS.map(item => [item.id, item.reverseScored ? 1 : 5]))
const report = buildReport(answers, { generatedAt: 1000 })
const insight = buildChapterInsight('C1', answers)

assert.equal(report.contentVersion, CONTENT_VERSION)
assert.equal(report.reportCopyVersion, REPORT_COPY_VERSION)
assert.equal(report.claims.every(claim => claim.contentVersion === CONTENT_VERSION), true)
assert.equal(insight.contentVersion, CONTENT_VERSION)
assert.ok(insight.lead && insight.reflection)
assert.equal(getChapterCopy('C6').contentVersion, CONTENT_VERSION)
assert.equal(rules.every(rule => rule.copyKey && !Object.prototype.hasOwnProperty.call(rule, 'text')), true)
assert.ok(resolveClaimCopy('COMB_STATUS_01').title)

const pageText = file => fs.readFileSync(path.join(__dirname, '..', file), 'utf8')
const stagePage = pageText('pages/chapter-insight/index.wxml')
const reportPage = pageText('pages/questionnaire-result/index.wxml')
const claimPage = pageText('pages/record-claim/index.wxml')
const app = JSON.parse(fs.readFileSync(path.join(__dirname, '..', 'app.json'), 'utf8'))
const publicPages = app.pages.map(route => pageText(route + '.wxml')).join('\n')
;['阶段发现', '多题支持', '规则 {{claim.reportRuleVersion', '相处名片', '关系资源', '内部拉扯'].forEach(copy => {
  assert.equal(publicPages.includes(copy), false, `forbidden user copy: ${copy}`)
})
assert.equal(stagePage.includes('evidenceCopy.why'), true)
assert.equal(claimPage.includes('evidenceCopy.supporting'), true)

console.log('Content experience OK: versioned copy, reflective stage insight, and internal labels stay hidden')
