const assert = require('node:assert/strict')
const { ITEMS } = require('../utils/assessment-v2/questionnaire-definitions')
const { buildReport } = require('../utils/assessment-v2/report-engine')

const answers = Object.fromEntries(ITEMS.map(item => [item.id, item.reverseScored ? 1 : 5]))
const normal = buildReport(answers, { responseQuality: { status: 'normal' } })
const review = buildReport(answers, { responseQuality: { status: 'review_recommended' } })
const limited = buildReport(answers, { responseQuality: { status: 'limited_evidence' } })
assert.ok(normal.claims.some(claim => claim.confidence.level === 'strong'))
assert.equal(review.claims.some(claim => claim.confidence.level === 'strong'), false)
assert.equal(limited.claims.some(claim => claim.confidence.level === 'strong'), false)
assert.ok(review.claims.every(claim => claim.confidence.reasonCodes.includes('response_quality_review')))
assert.ok(limited.claims.every(claim => claim.confidence.reasonCodes.includes('limited_response_evidence')))
console.log('Report confidence OK: response quality lowers confidence without invalidating reports')
