const assert = require('node:assert/strict')
const { listFixtures } = require('../shared/assessment-v3-product/fixtures')
const { DIMENSION_IDS } = require('../shared/assessment-v3-product/contract')
const { buildReport } = require('../shared/assessment-v3-product/report-renderer')

listFixtures().forEach(fixture => {
  const report = buildReport(fixture)
  assert.equal(report.isSynthetic, true)
  assert.equal(report.source, 'synthetic_fixture')
  assert.deepEqual(report.dimensionCards.map(card => card.id), DIMENSION_IDS)
  assert.equal(report.dimensionCards.length, 14)
  assert.equal(report.chapterSyntheses.length, 6)
  assert.equal(report.chapterSyntheses.reduce((total, chapter) => total + chapter.dimensionIds.length, 0), 14)
  assert.ok(report.executiveSummary.patterns.length <= 3)
  assert.equal(report.decisionMap.sections.length, 3)
  assert.ok(report.decisionMap.sections.every(section => section.items.every(item => item.detail)))
  assert.ok(report.unknowns.items.length)
  assert.ok(report.interviewPriorities.items.length)
  const evidenceLabels = report.dimensionCards.flatMap(card => card.evidence.map(item => item.label))
  assert.ok(evidenceLabels.includes('支持这条理解'))
  assert.ok(evidenceLabels.includes('需要一起看的回答'))
  assert.ok(evidenceLabels.includes('不完全一致的回答'))
  assert.equal('score' in report, false)
  assert.equal('totalScore' in report, false)
  assert.equal('compatibility' in report, false)
  assert.equal('personalityType' in report, false)
})

console.log('V3 product report renderer OK: 12 synthetic profiles, 14 dimensions, 6 chapters')
