const assert = require('node:assert/strict')
const fs = require('node:fs')
const app = require('../app.json')
const { FEATURES } = require('../utils/features')
const { getFixture } = require('../shared/assessment-v3-product/fixtures')
const { createDerivedV3Profile } = require('../shared/assessment-v3-product/contract')
const { buildReport } = require('../shared/assessment-v3-product/report-renderer')

assert.equal(FEATURES.v3ProductPreview, true)
assert.equal(FEATURES.v3CalibratedProduction, false)
;['pages/v3-product-preview/index', 'pages/v3-checkpoint/index', 'pages/v3-result/index', 'pages/v3-result-evidence/index'].forEach(route => assert.ok(app.pages.includes(route), `${route} is not registered`))
assert.throws(() => createDerivedV3Profile({}), /Invalid DerivedV3Profile/)
const profile = getFixture('ready_self')
const report = buildReport(profile)
assert.equal(report.assessmentMeta.scoringModelVersion, 'synthetic-fixture')
assert.equal(report.isSynthetic, true)
assert.ok(report.decisionMap.sections.every(section => section.items.length > 0))
assert.equal(fs.readFileSync(require.resolve('../shared/assessment-v3-pilot/runtime-engine'), 'utf8').includes('node:crypto'), false)
const futureProfile = createDerivedV3Profile(Object.assign({}, profile, { source: 'calibrated_production', isSynthetic: false }))
assert.equal(buildReport(futureProfile).isSynthetic, false)

console.log('V3 report contract OK: synthetic boundary, route registration, no Node crypto')
