const REPORT_RULE_VERSION = 'serious-match-report-rules-2.1.0'

const rules = [
  ['COMB_STATUS_01', 'overall', '你不是不想开始，而是现实余力还没有完全跟上', [['readiness_intent.state','in',['strong_present','lean_present']],['available_capacity.state','in',['lean_less','strong_less']]], '你的关系意愿已经比较清楚，但近期时间、情绪带宽或生活变化可能影响稳定投入。更合适的做法不是否定自己的意愿，而是把可见面频率、联系窗口和忙碌说明讲清楚。', '这是当前状态组合，不是长期能力判断。', '想认真开始，正在安排现实空间'],
  ['COMB_STATUS_02', 'overall', '现实条件允许，但你本人未必急着进入关系', [['readiness_intent.state','in',['lean_less','strong_less']],['available_capacity.state','in',['lean_present','strong_present']]], '你似乎有时间和基本余力，但是否真正想进入承诺关系仍未完全确定。此时更重要的是确认自己愿意为什么样的关系投入。', '有时间不等于必须开始。', '不急着开始，更看重是否值得'],
  ['COMB_MOTIVATION_01', 'overall', '你有关系愿望，但外部推动也可能参与其中', [['readiness_intent.state','in',['strong_present','lean_present']],['autonomous_motivation.state','in',['lean_less','strong_less','mixed']]], '你并不是完全不想开始，只是家庭、年龄或周围节奏可能让这件事更紧迫。更适合保留自己的决定速度。', '外部推动不必然是坏事，关键是最终选择是否仍属于你。', '有认真愿望，也坚持自己的节奏'],
  ['COMB_UNCERTAINTY_01', 'interaction', '你会较快注意到距离变化，但也愿意直接确认', [['uncertainty_sensitivity.state','in',['strong_present','lean_present']],['observations.REG03','eq','active']], '回应节奏变化可能让你更快不安，不过你并不只能靠猜测；直接表达自己的注意和需要，可能是你很重要的关系资源。', '能直接表达不代表每次都能在强烈情绪下做到。', '重视清晰，也愿意直接说'],
  ['COMB_UNCERTAINTY_02', 'tension', '不确定时，反复确认可能暂时缓解不安', [['uncertainty_sensitivity.state','in',['strong_present','lean_present']],['observations.REG01','eq','active']], '当关系状态不清楚时，你可能会增加消息、追问或连续确认。这样能快速获得信息，也可能和对方的退开形成循环。', '这只是常见风险，不代表每次追问都不合适。', ''],
  ['COMB_UNCERTAINTY_03', 'tension', '你可能很在意距离变化，却在压力下先把自己收回去', [['uncertainty_sensitivity.state','in',['strong_present','lean_present']],['observations.REG02','eq','active']], '你对关系变化并不迟钝，但真正感到受伤或不安时，可能减少回应或搁置话题。对方看到的也许是冷淡，而不是你内部的不确定。', '不同对象和冲突强度下反应可能不同。', ''],
  ['COMB_DISTANCE_01', 'interaction', '你可能既需要确定，也需要靠近过程保持可控', [['uncertainty_sensitivity.state','in',['strong_present','lean_present']],['closeness_discomfort.state','in',['strong_present','lean_present']]], '关系不明确时，你希望尽快知道对方态度；但关系真正靠近时，你又可能需要放慢。这更像是同时重视安全感和边界。', '报告不能据此给你分配固定依恋类型。', '需要清晰，也需要有边界地靠近'],
  ['COMB_CLOSENESS_01', 'interaction', '你可以亲近，也希望双方保留各自生活', [['closeness_discomfort.state','in',['lean_less','strong_less']],['autonomy_space.needState','eq','need_clear']], '你并不排斥表达脆弱或相互依赖，同时仍需要独处、朋友和个人安排。对你来说，亲密和独立不是二选一。', '空间需求的具体程度仍需要在真实关系中协商。', '亲密与独立并重'],
  ['COMB_RESPONSE_01', 'resource', '你需要清楚回应，也通常能提供同样的连续性', [['response_predictability.needState','eq','need_clear'],['response_predictability.provideState','eq','provide_stable']], '你看重重要话题有说明、有下文；同时也倾向在忙碌时说明，并在暂停后回来。', '极度忙碌或强烈情绪下仍可能出现例外。', '不必一直聊天，但重要的话要有下文'],
  ['COMB_RESPONSE_02', 'tension', '你很需要回应有下文，但自己未必总能稳定做到', [['response_predictability.needState','eq','need_clear'],['response_predictability.provideState','in',['provide_variable','provide_constrained']]], '你希望对方在忙碌或暂停时给出说明；不过自己提供同样连续性的能力可能受情境影响。', '当前余力不足也可能造成这种差异，不宜解释为双重标准。', ''],
  ['COMB_SUPPORT_01', 'resource', '你重视先理解感受，也通常能这样回应别人', [['emotional_support.needState','eq','need_clear'],['emotional_support.provideState','eq','provide_stable']], '你希望情绪被听懂后再进入建议，同时也能先听完并询问对方需要陪伴还是办法。', '不同问题可能需要不同支持顺序。', '先理解，再一起解决'],
  ['COMB_SUPPORT_02', 'tension', '你希望先被理解，但帮助别人时可能更快进入解决问题', [['emotional_support.needState','eq','need_clear'],['emotional_support.provideState','in',['provide_variable','provide_constrained']]], '你对自己的情绪支持需要比较清楚；不过在对方低落时，你未必总能停留在倾听和确认阶段。', '是否提供得好，需要结合对方真实感受。', ''],
  ['COMB_SPACE_01', 'resource', '你需要个人空间，也通常愿意把空间给对方', [['autonomy_space.needState','eq','need_clear'],['autonomy_space.provideState','eq','provide_stable']], '你希望保留独处和个人安排，同时也能接受对方拥有自己的朋友、兴趣和节奏。', '在不安或冲突时，空间的含义可能发生变化。', '给彼此空间，但不是失去联系'],
  ['COMB_SPACE_02', 'tension', '你需要自己的空间，但对方退开时可能不容易同样安心', [['autonomy_space.needState','eq','need_clear'],['autonomy_space.provideState','in',['provide_variable','provide_constrained']]], '你清楚自己需要独处；不过当对方提出类似需要时，你的尊重程度可能受不安影响。', '只凭自评不能判断实际互动中谁更合理。', ''],
  ['COMB_CONFLICT_01', 'resource', '你能接受暂停，关键是明确会回来修复', [['conflict_pause.needState','eq','need_clear'],['conflict_pause.provideState','eq','provide_stable'],['repair_reengagement.provideState','eq','provide_stable']], '你不要求所有问题当场解决；只要暂停有说明、之后有人重新开启对话，你通常能够给彼此冷静空间。', '严重边界问题不应仅靠“冷静后再说”处理。', '可以先冷静，但一定要回来'],
  ['COMB_CONFLICT_02', 'tension', '你很需要冲突后有人主动修复，但自己受伤时未必容易先回来', [['repair_reengagement.needState','eq','need_clear'],['repair_reengagement.provideState','in',['provide_variable','provide_constrained']]], '你希望问题不要自然消失；不过在受伤或防御时，你主动重启和承认影响的稳定性可能下降。', '这可能受到当次冲突责任和安全程度影响。', ''],
  ['COMB_REGULATION_01', 'tension', '你在不同压力情境下可能既会追近，也会退开', [['observations.REG01','eq','active'],['observations.REG02','eq','active']], '有些时候你会通过追问获得确定，有些时候又会减少回应保护自己。报告会保留这种情境差异。', '需要通过具体事件核对哪些情境更容易触发哪种动作。', ''],
  ['COMB_RESOURCE_01', 'resource', '你拥有一套比较清楚的沟通与修复资源', [['observations.REG03','eq','active'],['observations.REG04','eq','active'],['repair_reengagement.provideState','eq','provide_stable']], '你能够直接表达不安，需要暂停时也会说明，冷静后还能重新回到问题。', '自评资源仍需在真实互动中验证。', '愿意说清，也愿意回来修复'],
  ['COMB_CAPACITY_01', 'tension', '当前状态可能影响你提供稳定回应', [['available_capacity.state','in',['lean_less','strong_less']],['response_predictability.provideState','in',['provide_variable','provide_constrained']]], '当时间或情绪余力不足时，即使你认同清楚沟通，也可能难以持续做到。', '待生活状态变化后应重新评估。', '']
].map(([id, section, title, conditions, text, boundary, shareFragment]) => ({ id, section, title, conditions, text, boundary, shareFragment }))

module.exports = { REPORT_RULE_VERSION, rules }
