const { CONTENT_VERSION, REPORT_COPY_VERSION } = require('./version')

module.exports = Object.freeze({
  CONTENT_VERSION,
  REPORT_COPY_VERSION,
  sections: Object.freeze([
    { id: 'overall', title: '现在的你' },
    { id: 'interaction', title: '关系有变化时' },
    { id: 'resource', title: '你希望怎样相处' },
    { id: 'provide', title: '你通常会怎么做' },
    { id: 'tension', title: '还有几件事，可以再想想' }
  ]),
  heroIntro: '这是根据你这次回答整理出的结果。先看最明显的几件事。',
  topFindingsTitle: '先看这 3 点',
  chapterResultsTitle: '再分开看看',
  chapterResultsDescription: '',
  detailsTitle: '更多结果',
  detailsDescription: '',
  detailsAction: '展开更多',
  detailsCollapseAction: '收起',
  unknownTitle: '还有几件事，现在看不出来',
  unknownDescription: '这些题的回答还不够一致，现在先不下结论。',
  observationTitle: '你平时可能会这样做',
  boundary: '这些结果只根据你这次的回答整理，不是心理诊断，也不能预测一段关系会不会成功。',
  reviseTitle: '修改回答',
  dataTitle: '数据和隐私',
  dataDelete: '删除这次结果',
  deleteDialogTitle: '删除这次结果？',
  deleteDialogContent: '问卷、结果和本机保存的副本都会删除。删除后不能恢复。',
  deleteDialogCancel: '取消',
  deleteDialogConfirm: '删除',
  mapAction: '继续看看你在意什么',
  followupTitle: '如果你愿意，可以再聊聊',
  followupBody: '有些事靠选择题问不清。我们会邀请一部分人做一对一访谈，也可能组织大连的线下交流。要不要参加都由你自己决定。',
  followupAction: '了解一下',
  claimAction: '为什么这么说',
  map: Object.freeze({
    kicker: '',
    title: '你在意什么',
    description: '',
    claimsTitle: '你比较在意的事',
    claimsDescription: '点开可以看看相关回答，或者回去修改。',
    unknownTitle: '还有些事，你现在还没想清楚',
    unknownDescription: '这几项现在先不下结论。',
    historyTitle: '以前的结果',
    historyDescription: '以前的回答会单独保留，不会覆盖现在这次。',
    followupKicker: '',
    followupTitle: '如果你愿意，可以把一两件事聊得更具体',
    followupDescription: '一对一访谈和线下交流都会另外说明，再由你决定要不要参加。',
    followupAction: '了解一下',
    reportAction: '回到你的结果',
    reportDescription: '',
    claimBasis: '为什么这么说'
  })
})
