const { CONTENT_VERSION, REPORT_COPY_VERSION } = require('./version')

module.exports = Object.freeze({
  CONTENT_VERSION,
  REPORT_COPY_VERSION,
  sections: Object.freeze([
    { id: 'overall', title: '现在的你' },
    { id: 'interaction', title: '关系有变化时' },
    { id: 'resource', title: '你希望怎样相处' },
    { id: 'provide', title: '你通常能给出的' },
    { id: 'tension', title: '值得再想一想的地方' }
  ]),
  heroIntro: '这是一份根据你这次回答整理出的关系快照。\n\n先看最重要的几件事，再按章节慢慢展开。',
  topFindingsTitle: '最值得注意的 3 件事',
  chapterResultsTitle: '六章结果',
  chapterResultsDescription: '从开始、投入、靠近到冲突，看看你的关系倾向怎样连在一起。',
  detailsTitle: '完整结果',
  detailsDescription: '想看每条结论的依据，可以从这里打开。',
  detailsAction: '查看完整结果',
  detailsCollapseAction: '收起完整结果',
  unknownTitle: '还有些地方，现在说不好',
  unknownDescription: '有些回答暂时没有形成清楚方向。先保留问题，比勉强补出结论更有用。',
  observationTitle: '值得留意的行动',
  boundary: '这份说明书来自你的自我回答，不是心理诊断。它可以帮你整理关系需要，但不能替代真实相处，也不能预测一段关系一定成功。',
  reviseTitle: '想改答案时',
  dataTitle: '数据管理',
  dataDelete: '删除这份关系说明书',
  deleteDialogTitle: '删除关系说明书？',
  deleteDialogContent: '云端问卷和报告、本机副本都会删除。删除后无法恢复。',
  deleteDialogCancel: '取消',
  mapAction: '打开你的关系决策地图',
  followupTitle: '如果你愿意，还可以继续聊',
  followupBody: '问卷先帮你整理出一些方向。真实经历里还有哪些细节，只有你自己最清楚。\n\n后续访谈、补充研究或线下活动都会单独说明并征求同意；是否参加，完全由你决定。',
  followupAction: '了解后续参与',
  claimAction: '查看依据',
  map: Object.freeze({
    kicker: '关系说明书 · 继续整理',
    title: '你的关系决策地图',
    description: '把这份说明书里反复出现的方向放在一起，看看你希望关系怎样运行。\n\n它会随着你修改回答而变化。',
    claimsTitle: '你选择伴侣时真正看重什么',
    claimsDescription: '逐条打开，可以查看依据或修改相关回答。',
    unknownTitle: '还想继续想想的地方',
    unknownDescription: '回答暂时不够时，先留一个问题。',
    historyTitle: '以前的版本',
    historyDescription: '旧版本保留当时的回答，不会覆盖现在这份。',
    followupKicker: '接下来由你决定',
    followupTitle: '把一两件事聊得更具体',
    followupDescription: '后续访谈、补充研究或线下活动都会单独说明并征求同意。',
    followupAction: '了解后续参与',
    reportAction: '回到完整说明书',
    reportDescription: '继续查看六章结果、依据和数据管理。',
    claimBasis: '查看依据'
  })
})
