const { CONTENT_VERSION, REPORT_COPY_VERSION } = require('./version')

module.exports = Object.freeze({
  CONTENT_VERSION,
  REPORT_COPY_VERSION,
  sections: Object.freeze([
    { id: 'overall', title: '现在的你' },
    { id: 'interaction', title: '关系一有变化时' },
    { id: 'resource', title: '你希望怎样相处' },
    { id: 'provide', title: '你通常能给出的' },
    { id: 'tension', title: '有几个地方值得多看一眼' }
  ]),
  confirmationLabels: Object.freeze({ fits: '很像', partly_fits: '有一点像', does_not_fit: '不太像', unsure: '说不好' }),
  heroIntro: '下面不是给你分类型。\n\n我们只是把这次回答放到一起，看哪些东西反复出现，哪些地方彼此有点矛盾。\n\n先从最明显的说。',
  unknownTitle: '还有些地方，现在说不好。',
  unknownDescription: '有些题你暂时没有足够经验，或者回答还没有形成很清楚的方向。\n\n这部分先留着，比硬下一个结论更有用。',
  observationTitle: '还有一个动作值得注意',
  boundary: '这份说明书来自你的自我回答，不是心理诊断。它能帮你整理关系需要，但不能替代真实相处，也不能预测一段关系一定成功。',
  reviseTitle: '修改我的回答',
  dataTitle: '数据管理',
  dataDelete: '删除这份关系说明书',
  deleteDialogTitle: '删除关系说明书？',
  deleteDialogContent: '云端问卷、报告和核对记录都会删除，本机副本也会同时清除。删除后无法恢复。',
  deleteDialogCancel: '取消',
  mapAction: '看看我目前比较确定的',
  followupTitle: '如果你愿意，我们还可以聊得更具体一点。',
  followupBody: '问卷能看见一些规律。\n\n但很多东西只有讲到真实经历时，才会真的变清楚。\n\n我们会邀请一部分用户做一对一访谈，也可能组织一些大连的线下交流。\n\n要不要参加，完全由你决定。',
  followupAction: '了解一下',
  claimAction: '打开看看这句话怎么来的',
  map: Object.freeze({
    kicker: '你的关系说明书 · 可以继续修改',
    title: '我目前比较确定的',
    description: '这些是你已经答过、也核对过的一些内容。\n\n关系经历变化以后，它们本来就可能变化。',
    claimsTitle: '目前比较明显的',
    claimsDescription: '每句话都可以打开、核对或改掉。',
    confirmedTitle: '你自己也觉得比较像的',
    confirmedDescription: '这些是你已经看过并回应过的描述。',
    unknownTitle: '暂时还说不清的',
    unknownDescription: '回答不够时，先保留问题，不急着补出结论。',
    historyTitle: '以前的版本',
    historyDescription: '旧版本保留当时的回答，不会覆盖现在这份。',
    followupKicker: '接下来由你决定',
    followupTitle: '如果愿意，可以把一两件事聊得更具体',
    followupDescription: '问卷能看见一些规律，真实经历通常会让它更清楚。后续访谈、研究或线下活动都会单独说明并征求同意。',
    followupAction: '了解一下',
    reportAction: '回到完整说明书',
    reportDescription: '逐条查看、核对或修改你的回答',
    claimBasis: '打开这句话的依据'
  })
})
