const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')

const root = path.resolve(__dirname, '..')
const read = file => fs.readFileSync(path.join(root, file), 'utf8')
const app = JSON.parse(read('app.json'))
const packageJson = JSON.parse(read('package.json'))
const cloud = read('cloudfunctions/datingProfile/index.js')
const features = read('utils/features.js')
const privacy = read('pages/privacy/index.wxml')
const collections = read('design/CLOUD_COLLECTIONS.md')

assert.equal(packageJson.version, '2.1.0-pilot-interview')
;['pages/followup-intro/index', 'pages/followup-profile/index', 'pages/followup-settings/index'].forEach(route => assert.ok(app.pages.includes(route), route))
;['pages/compare/index', 'pages/profile-preview/index', 'pages/contact/index', 'pages/profile/index'].forEach(route => assert.equal(app.pages.includes(route), false, route))
;['friendComparison: false', 'matchingProfile: false', 'matchingPool: false', 'followupParticipation: true', 'interviewResearchConsent: true'].forEach(value => assert.ok(features.includes(value), value))
;['assessmentFeedbackAppend', 'consentGrant', 'consentRevoke', 'participantUpsert', 'participantDelete', 'caseCreate', 'participantContactReveal', 'preparationGenerate', 'validationAppend', 'questionUnderstandingAppend', 'deidentifiedExport', 'pilotMetrics', 'requireOperator', 'appendAudit'].forEach(value => assert.ok(cloud.includes(value), value))
;['assessment_sessions', 'assessment_reports', 'assessment_feedback_events', 'consent_events', 'participant_registry', 'participant_contacts', 'interview_cases', 'interview_validation_events', 'operator_accounts', 'audit_events'].forEach(value => assert.ok(collections.includes(value), value))
;['默认均不勾选', '联系方式隔离保存', '随时撤回或删除'].forEach(value => assert.ok(privacy.includes(value), value))
assert.ok(fs.existsSync(path.join(root, '.github/workflows/test.yml')))
console.log('v2.1 Definition of Done static audit OK')
